-- Criar tabela codigos_tres
CREATE TABLE IF NOT EXISTS public.codigos_tres (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text NOT NULL,
  usado boolean NOT NULL DEFAULT false,
  criado_em timestamptz NOT NULL DEFAULT now(),
  usado_em timestamptz
);

ALTER TABLE public.codigos_tres ENABLE ROW LEVEL SECURITY;

CREATE POLICY codigos_tres_admin_all
ON public.codigos_tres
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);