-- Criar tabela tela_descanso
CREATE TABLE IF NOT EXISTS public.tela_descanso (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ativa boolean NOT NULL DEFAULT true,
  imagem_url text NULL,
  titulo text NULL,
  subtitulo text NULL,
  cor_fundo text NULL,
  criado_em timestamptz NOT NULL DEFAULT now()
);

-- Inserir registro padrão
INSERT INTO public.tela_descanso (ativa, titulo, subtitulo, cor_fundo)
VALUES (false, 'Bem-vindo ao Mercadinho', 'Toque para iniciar', '#1a1a2e');

-- Criar bucket para imagens da tela de descanso
INSERT INTO storage.buckets (id, name, public)
VALUES ('tela-descanso', 'tela-descanso', true)
ON CONFLICT (id) DO NOTHING;

-- Política para leitura pública
CREATE POLICY "Imagens tela descanso são públicas"
ON storage.objects FOR SELECT
USING (bucket_id = 'tela-descanso');

-- Política para upload (qualquer um pode fazer upload por enquanto - admin)
CREATE POLICY "Permitir upload tela descanso"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'tela-descanso');

-- Política para deletar
CREATE POLICY "Permitir deletar tela descanso"
ON storage.objects FOR DELETE
USING (bucket_id = 'tela-descanso');