-- Adicionar quantidade_atual em produtos
ALTER TABLE public.produtos 
ADD COLUMN IF NOT EXISTS quantidade_atual integer NOT NULL DEFAULT 0;

-- Criar tabela lotes_produtos
CREATE TABLE IF NOT EXISTS public.lotes_produtos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id bigint NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  quantidade integer NOT NULL,
  validade date NULL,
  preco_compra_lote numeric(12,2) NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  ativo boolean NOT NULL DEFAULT true
);

-- Criar tabela promocoes
CREATE TABLE IF NOT EXISTS public.promocoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  desconto_percentual numeric(5,2) NOT NULL,
  tipo text NOT NULL CHECK (tipo IN ('global', 'produto')),
  produto_id bigint NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  inicia_em timestamptz NOT NULL,
  termina_em timestamptz NULL,
  ativa boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now()
);

-- Criar índices para performance
CREATE INDEX IF NOT EXISTS idx_lotes_produtos_produto_id ON public.lotes_produtos(produto_id);
CREATE INDEX IF NOT EXISTS idx_promocoes_produto_id ON public.promocoes(produto_id);
CREATE INDEX IF NOT EXISTS idx_promocoes_ativa ON public.promocoes(ativa, inicia_em, termina_em);