-- Tabela de abatimentos (descontos aplicados na dívida do cliente)
CREATE TABLE public.abatimentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id bigint NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
  valor numeric NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now()
);

-- RLS
ALTER TABLE public.abatimentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "abatimentos_select_anon" ON public.abatimentos
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "abatimentos_admin_all" ON public.abatimentos
  FOR ALL TO authenticated USING (true) WITH CHECK (true);