CREATE TABLE public.retiradas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id bigint NOT NULL REFERENCES public.produtos(id),
  quantidade integer NOT NULL,
  origem text NOT NULL,
  motivo text NOT NULL,
  descricao text NOT NULL,
  preco_compra_snapshot numeric,
  preco_venda_snapshot numeric NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.retiradas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "retiradas_select_anon" ON public.retiradas
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "retiradas_admin_all" ON public.retiradas
  FOR ALL TO authenticated USING (true) WITH CHECK (true);