-- =====================================================================
-- Estrutura base para reservas temporárias de checkout PIX
-- Nenhuma estrutura existente é alterada. Sem dados, funções ou triggers.
-- =====================================================================

CREATE TABLE public.reservas_checkout (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  criado_em          timestamptz NOT NULL DEFAULT now(),
  mercadinho_id      bigint      NOT NULL,
  cliente_id         bigint      NULL,
  tablet_id          bigint      NULL,
  forma_pagamento    text        NOT NULL,
  valor_total        numeric     NOT NULL,
  chave_idempotencia uuid        NOT NULL,
  expira_em          timestamptz NOT NULL DEFAULT (now() + interval '3 minutes'),
  confirmada_em      timestamptz NULL,
  cancelada_em       timestamptz NULL,

  CONSTRAINT reservas_checkout_chave_idempotencia_key UNIQUE (chave_idempotencia),
  CONSTRAINT reservas_checkout_mercadinho_id_fkey
    FOREIGN KEY (mercadinho_id) REFERENCES public.mercadinhos(id),
  CONSTRAINT reservas_checkout_cliente_id_fkey
    FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT reservas_checkout_tablet_id_fkey
    FOREIGN KEY (tablet_id) REFERENCES public.tablets(id),

  CONSTRAINT reservas_checkout_forma_pagamento_check CHECK (forma_pagamento = 'pix'),
  CONSTRAINT reservas_checkout_valor_total_check      CHECK (valor_total >= 0),
  CONSTRAINT reservas_checkout_expira_em_check        CHECK (expira_em > criado_em),
  CONSTRAINT reservas_checkout_estado_check
    CHECK (NOT (confirmada_em IS NOT NULL AND cancelada_em IS NOT NULL))
);

ALTER TABLE public.reservas_checkout ENABLE ROW LEVEL SECURITY;

CREATE INDEX reservas_checkout_pendentes_expira_idx
  ON public.reservas_checkout (mercadinho_id, expira_em)
  WHERE confirmada_em IS NULL
    AND cancelada_em IS NULL;

CREATE TABLE public.reservas_checkout_itens (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id     bigint      NOT NULL,
  prateleira_id  bigint      NOT NULL,
  quantidade     integer     NOT NULL,
  valor_unitario numeric     NOT NULL,
  valor_total    numeric     NOT NULL,
  criado_em      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT reservas_checkout_itens_reserva_id_fkey
    FOREIGN KEY (reserva_id) REFERENCES public.reservas_checkout(id) ON DELETE CASCADE,
  CONSTRAINT reservas_checkout_itens_prateleira_id_fkey
    FOREIGN KEY (prateleira_id) REFERENCES public.prateleiras_produtos(id),

  CONSTRAINT reservas_checkout_itens_reserva_prateleira_key
    UNIQUE (reserva_id, prateleira_id),

  CONSTRAINT reservas_checkout_itens_quantidade_check     CHECK (quantidade > 0),
  CONSTRAINT reservas_checkout_itens_valor_unitario_check CHECK (valor_unitario >= 0),
  CONSTRAINT reservas_checkout_itens_valor_total_check    CHECK (valor_total >= 0),
  CONSTRAINT reservas_checkout_itens_consistencia_check
    CHECK (valor_total = valor_unitario * quantidade)
);

ALTER TABLE public.reservas_checkout_itens ENABLE ROW LEVEL SECURITY;

CREATE INDEX reservas_checkout_itens_prateleira_idx
  ON public.reservas_checkout_itens (prateleira_id);